### ISSUE TITLE
Plugin creating another root instance

### ISSUE THREAD

**Issue by DouglasAR01** [Tahul/vue-my-toasts#11]
Hello. 
I'm trying to test this plugin in a project, however, for some reason, the plugin is creating another Vue app instance (or that's what I think it's going on). An image speak more than a thousand words, there are two Root components:
![image](https://user-images.githubusercontent.com/33143337/109256402-efc62380-77c3-11eb-8192-38589343da60.png)
This is part of my app.js code:
![image](https://user-images.githubusercontent.com/33143337/109256496-197f4a80-77c4-11eb-9d6c-109e0c5a611e.png)
![image](https://user-images.githubusercontent.com/33143337/109256518-23a14900-77c4-11eb-8175-646e6c6dddcc.png)
This is the index blade template page (I'm using Laravel as backend with Laravel-mix, that's why the following image is a blade template):
![image](https://user-images.githubusercontent.com/33143337/109256559-374caf80-77c4-11eb-8344-059f86428b7b.png)
I'm not sure if that behavior is a bug or maybe I'm missing something. 
Thank you!

**Comment by mediv0** [comment]
hi

this is not a bug

 this package will render toast component in a different place in the DOM tree, not in the app's scope.
this is very handy when working with modals, notifications because you don't want your toast to be nested inside another DOM element

**Comment by DouglasAR01** [comment]
Okay, thank you.
