### ISSUE TITLE
Class based vue

### ISSUE THREAD

**Issue by dennmat-hurdle** [Tahul/vue-my-toasts#13]
Im using classes with Vue to take advantage of TypeScript and because component is typed as Object when it receives the class based component it is a Function this throws a warning(its just a warning so it still works fine). 

`[Vue warn]: Invalid prop: type check failed for prop "component". Expected Object, got Function `

Would be nice to get Function added as an acceptable type.
Great library by the way!

**Comment by mediv0** [comment]
hi, 
this is because of #10 

@Tahul  if this is ok with you I can make a fix

**Comment by mediv0** [comment]
Actually made an RP, to avoid wasting time
@Tahul pls check

**Comment by Tahul** [comment]
Hey @mediv0 ; looking at this right now :)

**Comment by Tahul** [comment]
Hey @dennmat-hurdle;

Your issue has been fixed by @mediv0, it is availabie in 1.1.1.

I'm closing this right now, feel free to re-open if needed. 👋

**Comment by dennmat-hurdle** [comment]
Amazing :) thanks!
