### ISSUE TITLE
Event "remove" is triggered at infinity

### ISSUE THREAD

**Issue by Melvin-klein** [Tahul/vue-my-toasts#7]
Hello,

Thanks for your plugin ! :+1: 

I'm using it on a VueJS Electron App. When a toast is removed, the event "remove" is still triggered.

Number of events is incrementing at infinity :

![Capture d’écran_2021-01-23_10-37-30](https://user-images.githubusercontent.com/14358809/105574791-365cd400-5d67-11eb-880f-94d551010d12.png)

Events : 

![Capture d’écran_2021-01-23_10-38-15](https://user-images.githubusercontent.com/14358809/105574794-38269780-5d67-11eb-91da-ca59457305fd.png)

Is it the normal behavior ?

VueJS : v2
Electron : v9

**Comment by darthsoup** [comment]
There is a bug in the TimerMixin. After the `remove` event is called the recursion is continue his process because the break is missing.

**Comment by Tahul** [comment]
Thank you a lot, I'll be investigating this in the evening.

This looks like a bug from TimerMixin.

**Comment by Tahul** [comment]
Looks like it is linked to that: https://github.com/Tahul/vue-my-toasts/pull/8

The PR has been merged, sorry for the late answer, was busy lately. 🤗

You can try 1.1.0 which contains the fix!
