### ISSUE TITLE
Question about User component

### ISSUE THREAD

**Issue by mediv0** [Tahul/vue-my-toasts#9]
hi, 
I was checking the code and came across this section

https://github.com/Tahul/vue-my-toasts/blob/b464d291dec2d5b6a7972b05d44e8697223d8ae5/src/lib/injectComponent.js#L10-L11

Is there a specific reason for installing user component globally?

I think it's better to install it locally just for the Toast container to prevent any conflict in a large codebase

let me know what you think about this

**Comment by mediv0** [comment]
@Tahul 
also, I created an RP for it  ( https://github.com/Tahul/vue-my-toasts/pull/10 )

**Comment by Tahul** [comment]
Hello @mediv0 ;

Sorry I noticed you PR just now, I'll be merging this in the evening.

That's a nice feedback, thank you a lot for your contribution.

**Comment by Tahul** [comment]
I just added your fix in 1.1.0, thank you a lot!
